USE NetworkApp;

CREATE TABLE Users (
    id INT PRIMARY KEY IDENTITY(1,1),
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    coverpic VARCHAR(255),
    profilepic VARCHAR(255),
    city VARCHAR(255),
    website VARCHAR(45),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME DEFAULT GETDATE()
);

CREATE TABLE Posts
(
    id INT PRIMARY KEY IDENTITY(1,1),
    description VARCHAR(255) NOT NULL,
    img VARCHAR(200) NOT NULL,
    UserId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(id),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME DEFAULT GETDATE(),
);

SELECT *
from Posts
DROP TABLE Posts
SELECT *
FROM Users

CREATE TABLE Comments
(
    id INT PRIMARY KEY IDENTITY(1,1),
    description VARCHAR(255) NOT NULL,
    UserId INT NOT NULL,
    PostId INT NOT NULL,
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES Users(id),
    FOREIGN KEY (PostId) REFERENCES Posts(id),
);

DROP TABLE Comments
SELECT *
FROM Comments

CREATE TABLE Stories
(
    id INT PRIMARY KEY IDENTITY(1,1),
    img VARCHAR(255),
    UserId INT NOT NULL,
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES Users(id),

);
CREATE TABLE Relationship
(
    id INT PRIMARY KEY IDENTITY(1,1),
    followUserId INT NOT NULL,
    FollowerUserId INT NOT NULL,
    FOREIGN KEY (followUserId) REFERENCES Users(id),
    FOREIGN KEY (FollowerUserId) REFERENCES Users(id)
);
CREATE TABLE Likes
(
    id INT PRIMARY KEY IDENTITY(1,1),
    UserId INT NOT NULL,
    PostId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(id),
    FOREIGN KEY (PostId) REFERENCES Posts(id),
);